# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('title', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postSlug', models.SlugField(unique=True)),
                ('postText', models.TextField(max_length=2000)),
                ('postCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('postUpdatedAt', models.DateTimeField(auto_now=True)),
                ('postTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.Title')),
                ('postUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
