# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stashText', models.TextField(max_length=200)),
                ('stashCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('stashUpdatedAt', models.DateTimeField(auto_now=True)),
                ('stashTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.Title')),
                ('stashUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StashImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stashImageText', models.TextField(max_length=20)),
                ('stashImageCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('stashImageUpdatedAt', models.DateTimeField(auto_now=True)),
                ('stashImageStash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stash.Stash')),
            ],
        ),
        migrations.CreateModel(
            name='StashUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stashUrlText', models.TextField(max_length=200)),
                ('stashUrlCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('stashUrlUpdatedAt', models.DateTimeField(auto_now=True)),
                ('stashUrlStash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stash.Stash')),
            ],
        ),
    ]
