# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stash',
            name='stashSlug',
        ),
    ]
