# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stashimage',
            name='stashImageStash',
        ),
        migrations.RemoveField(
            model_name='stashurl',
            name='stashUrlStash',
        ),
        migrations.AddField(
            model_name='stash',
            name='stashUrl',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stash.StashUrl'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StashImage',
        ),
    ]
