# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleLengthText', models.TextField(max_length=100)),
                ('titleLengthLength', models.PositiveIntegerField(default=0)),
                ('titleTextCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('titleTextUpdatedAt', models.DateTimeField(auto_now=True)),
                ('titleLengthTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.Title')),
            ],
        ),
    ]
