# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('title', '0001_initial'),
        ('base', '0001_initial'),
        ('post', '0001_initial'),
        ('stash', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridgeCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('bridgeUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contentsprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('postprofileCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('postprofileUpdatedAt', models.DateTimeField(auto_now=True)),
                ('basic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Base')),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('stash', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stash.Stash')),
                ('title', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='title.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('flowUpdatedAt', models.DateTimeField(auto_now=True)),
                ('flowedContentsProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Contentsprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userprofileCalledName', models.TextField(max_length=30)),
                ('userprofileImage', models.ImageField(blank=True, upload_to='')),
                ('userprofileDescription', models.TextField(max_length=100)),
                ('userprofileCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('userprofileUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='flowingUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Userprofile'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='bridgedUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridgedUserProfile', to='info.Userprofile'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='bridgingUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridgingUserProfile', to='info.Userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together=set([('flowingUserProfile', 'flowedContentsProfile')]),
        ),
        migrations.AlterUniqueTogether(
            name='bridge',
            unique_together=set([('bridgingUserProfile', 'bridgedUserProfile')]),
        ),
    ]
