# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20170602_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basevoted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('basePro', models.PositiveIntegerField(default=0)),
                ('baseCon', models.PositiveIntegerField(default=0)),
                ('baseStage', models.PositiveIntegerField(default=0)),
                ('baseBlinded', models.PositiveSmallIntegerField(default=1)),
                ('profileCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('profileUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stashvoted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('stashPro', models.PositiveIntegerField(default=0)),
                ('stashCon', models.PositiveIntegerField(default=0)),
                ('stashStage', models.PositiveIntegerField(default=0)),
                ('stashBlinded', models.PositiveSmallIntegerField(default=1)),
                ('profileCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('profileUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usercalledname',
            fields=[
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.Userprofile')),
                ('userprofileCalledName', models.TextField(max_length=30)),
                ('userprofileDescription', models.TextField(max_length=100)),
                ('userprofileCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('userprofileUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userimage',
            fields=[
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.Userprofile')),
                ('userprofileImage', models.ImageField(blank=True, upload_to='')),
                ('userprofileDescription', models.TextField(max_length=100)),
                ('userprofileCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('userprofileUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='baseBlinded',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='baseCon',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='basePro',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='baseStage',
        ),
        migrations.RemoveField(
            model_name='stashprofile',
            name='stashBlinded',
        ),
        migrations.RemoveField(
            model_name='stashprofile',
            name='stashCon',
        ),
        migrations.RemoveField(
            model_name='stashprofile',
            name='stashPro',
        ),
        migrations.RemoveField(
            model_name='stashprofile',
            name='stashStage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userprofileCalledName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userprofileImage',
        ),
        migrations.AddField(
            model_name='stashvoted',
            name='stashprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.Stashprofile'),
        ),
        migrations.AddField(
            model_name='basevoted',
            name='baseprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.Baseprofile'),
        ),
    ]
