# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('stash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(max_length=200)),
                ('commentSlug', models.SlugField(unique=True)),
                ('commentCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('commentUpdatedAt', models.DateTimeField(auto_now=True)),
                ('commentBase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Base')),
                ('commentPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('commentStash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stash.Stash')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
